---

- name: Install python & nginx containers, run nmap command and check accessibility
  hosts: all
  tasks:

    - name: pull the necessary files to install the containers
      git:
        repo: https://github.com/TonySchneider/psys_exersice.git
        dest: psys_exersice

    - name: run docker-compose
      shell: docker-compose up -d
      args:
        chdir: psys_exersice/
