version: '3'
services:
    hercules:
        # build: hercules
        image: tonysch05/nginx_ssh:latest
        container_name: hercules_container
        ports:
            - "80:80"
            - "2222:22"
        volumes:
            - /mnt/logs/hercules:/var/log
        networks:
            vpcbr:
                ipv4_address: 172.20.0.2
    neptune:
        # build: neptune
        image: tonysch05/python_ssh:latest
        container_name: neptune_container
        ports:
            - "2211:22"
        volumes:
            - /mnt/logs/neptune:/var/log
        networks:
            vpcbr:
                ipv4_address: 172.20.0.3
networks:
  vpcbr:
    ipam:
      config:
        - subnet: 172.20.0.0/24